import { BackButton } from '../components/BackButton'
import licenseData from '../legal/licenses.generated.json'

// Open-source notices: one collapsible entry per production dependency,
// generated by `npm run generate:licenses` (scripts/generate-licenses.mjs)
// from node_modules — never hand-typed, so it can't drift from what's
// actually shipped. Plus content credits for non-npm material per
// docs/rnd/foss-fitness/LICENSE_REGISTER.md.
const LAST_UPDATED = '2026-10-01'

type LicensePackage = {
  name: string
  version: string
  license: string | null
  licenseText: string | null
  homepage: string | null
}

type ContentCredit = {
  name: string
  attribution: string
  license: string
  note: string
  homepage: string | null
}

const packages = licenseData.packages as LicensePackage[]
const contentCredits = licenseData.contentCredits as ContentCredit[]

export function LicensesScreen() {
  return (
    <div className="p-4 space-y-4 text-sm">
      <BackButton />
      <h1 className="text-xl font-bold">Open-source licenses</h1>
      <p className="text-xs text-ink-muted">Last updated {new Date(LAST_UPDATED).toLocaleDateString()}</p>

      <p className="text-ink-muted">
        Foundation Strength is built with the open-source software and content below. Thank you to everyone who
        makes their work available this way.
      </p>

      <section className="space-y-2">
        <h2 className="font-semibold">Content credits</h2>
        <div className="space-y-2">
          {contentCredits.map((credit) => (
            <div key={credit.name} className="card space-y-1 p-3">
              <p className="flex items-baseline gap-1 font-semibold">
                <span>{credit.name}</span>
                <span className="font-normal text-ink-muted">({credit.license})</span>
              </p>
              <p className="text-ink-muted">{credit.note}</p>
              <p className="text-xs text-ink-muted">{credit.attribution}</p>
            </div>
          ))}
        </div>
      </section>

      <section className="space-y-2">
        <h2 className="font-semibold">Software packages ({packages.length})</h2>
        <div className="space-y-2">
          {packages.map((pkg) => (
            <details key={pkg.name} className="group card p-3 [&_summary]:cursor-pointer">
              <summary className="flex min-h-11 list-none items-center justify-between font-semibold [&::-webkit-details-marker]:hidden">
                <span className="flex items-baseline gap-1">
                  <span>{pkg.name}</span>
                  <span className="font-normal text-ink-muted">v{pkg.version}</span>
                </span>
                <span className="flex items-center gap-2">
                  <span className="text-xs font-normal text-ink-muted">{pkg.license ?? 'unknown'}</span>
                  <span className="text-ink-muted transition-transform group-open:rotate-90" aria-hidden>
                    ›
                  </span>
                </span>
              </summary>
              <div className="space-y-2 pt-3">
                {pkg.homepage && (
                  <p className="text-xs text-ink-muted break-all">{pkg.homepage}</p>
                )}
                {pkg.licenseText ? (
                  <pre className="max-h-64 overflow-auto whitespace-pre-wrap rounded-control bg-field-primary p-2 text-xs text-ink-muted">
                    {pkg.licenseText}
                  </pre>
                ) : (
                  <p className="text-xs text-ink-muted">No license text was found for this package.</p>
                )}
              </div>
            </details>
          ))}
        </div>
      </section>
    </div>
  )
}
