#!/usr/bin/env bash
# Generates a new Android app-signing ("upload") keystore for Foundation
# Strength release builds, and writes android/keystore.properties pointing
# at it so `npm run apk:release` / `npm run aab` can sign with it.
#
# NOT run automatically by anything — the app owner runs this once, by hand,
# because only they should hold the key. Re-running it never overwrites an
# existing keystore (it refuses if one is already at the target path).
#
# Keystore + keystore.properties live outside the repo / are git-ignored:
#   - keystore file:      ~/Android/keys/foundation-strength-upload.jks
#   - keystore.properties: android/keystore.properties (git-ignored)
#
# BACK UP the keystore file and its passwords somewhere durable (password
# manager + an offline copy) the moment this finishes. Losing this key means
# you can never again publish an update to the same Play Store listing for
# app.foundationstrength.workout — Play Store app-signing keys cannot be
# recovered or reset by Google once lost (for apps that pre-date, or opt out
# of, Play App Signing's key-upgrade flow).
#
# Usage: scripts/make-keystore.sh [alias]
#   alias defaults to "foundation-strength"
#
# Needs `keytool` (ships with the JDK). Defaults to the JDK 21 at
# ~/Android/jdk21/bin/keytool if `keytool` isn't already on PATH.
set -euo pipefail
cd "$(dirname "$0")/.."

ALIAS="${1:-foundation-strength}"
KEY_DIR="$HOME/Android/keys"
KEYSTORE_PATH="$KEY_DIR/foundation-strength-upload.jks"
PROPERTIES_PATH="android/keystore.properties"

if [ -f "$KEYSTORE_PATH" ]; then
  echo "Keystore already exists at $KEYSTORE_PATH — refusing to overwrite it." >&2
  echo "Delete or move it first if you really want a new key (this invalidates the old one)." >&2
  exit 1
fi

if [ -f "$PROPERTIES_PATH" ]; then
  echo "$PROPERTIES_PATH already exists — refusing to overwrite it." >&2
  exit 1
fi

KEYTOOL="keytool"
if ! command -v "$KEYTOOL" >/dev/null 2>&1; then
  KEYTOOL="$HOME/Android/jdk21/bin/keytool"
fi
if ! command -v "$KEYTOOL" >/dev/null 2>&1; then
  echo "keytool not found (tried PATH and $HOME/Android/jdk21/bin/keytool)." >&2
  exit 1
fi

mkdir -p "$KEY_DIR"
chmod 700 "$KEY_DIR"

echo "Creating upload keystore at $KEYSTORE_PATH (alias: $ALIAS)."
echo "keytool will prompt for a keystore password, a key password, and your name/org details."
echo "Use a strong, unique password and store it in a password manager."
echo

"$KEYTOOL" -genkeypair \
  -v \
  -keystore "$KEYSTORE_PATH" \
  -alias "$ALIAS" \
  -keyalg RSA \
  -keysize 2048 \
  -validity 10000

chmod 600 "$KEYSTORE_PATH"

echo
echo "Keystore created. Now re-enter the same passwords so they can be saved"
echo "into $PROPERTIES_PATH (git-ignored, read by android/app/build.gradle)."
echo

read -r -s -p "Keystore password: " STORE_PASSWORD
echo
read -r -s -p "Key password for alias '$ALIAS' (press Enter if same as keystore password): " KEY_PASSWORD
echo
if [ -z "$KEY_PASSWORD" ]; then
  KEY_PASSWORD="$STORE_PASSWORD"
fi

cat > "$PROPERTIES_PATH" <<EOF
# Generated by scripts/make-keystore.sh — DO NOT COMMIT (git-ignored).
# Read by android/app/build.gradle's release signingConfig.
storeFile=$KEYSTORE_PATH
storePassword=$STORE_PASSWORD
keyAlias=$ALIAS
keyPassword=$KEY_PASSWORD
EOF
chmod 600 "$PROPERTIES_PATH"

echo
echo "Wrote $PROPERTIES_PATH."
echo "Back up $KEYSTORE_PATH and the passwords above right now (password manager + an"
echo "offline copy of the .jks file). This key must sign every future Play Store release."
echo
echo "Next: npm run apk:release   (signed release APK)"
echo "      npm run aab           (signed release AAB for Play Store)"
